### ISSUE TITLE
ヘッダーの見通しを建てる

### ISSUE THREAD

**Issue by kohkubo** [kohkubo/webserv#11]

**Comment by ryojiroakiyama** [comment]
見通しに必要な情報
- クライアントから何がほしいか
    - メソッド
    - URI
- サーバが何を返すか
    - ステータスコード
    - データ

**Comment by ryojiroakiyama** [comment]
見通しに必要な情報その2
サーバが何を返すか
- ステータスライン
    - HTTPバージョン
    - ステータスコード
    - レスポンスフレーズ
- メッセージヘッダー
    - フィールド名
        - "Content-type"など色々
    - フィールド値
        - "text/html"など色々
- メッセージボディ
    - ボディ(バイナリデータとして扱う?)
        - GETで指定されたファイルから読み出したデータ
        - POSTで指定されたCGIアプリなどが出力したデータ


形式
```
HTTPバージョン ステータスコード レスポンスフレーズ      ステータスライン
フィールド名:フィールド値                          メッセージヘッダー
.
.
.

ボディ                                        メッセージボディ
```
