### ISSUE TITLE
config構造 (サーバディレクティブ複数あるときのパターン)

### ISSUE THREAD

**Issue by nakamo326** [kohkubo/webserv#111]
std::map<listen_fd, std::vector<server_config>>
ポートに対してマッチングするserver_configのリストを持つ。
serverディレクティブの中にはrootなし、
locationは複数ある。（とりあえず一つ。

**Comment by nakamo326** [comment]
std::map<listen_fd, std::vector<Server_config>>はパースの段階で作るのが難しい。（パース時にはソケットは開いていないので）
とりあえず、Server_config.listen_port_をキーにしたmapのほうが実装は簡単そう。

**Comment by ryojiroakiyama** [comment]
serverディレクティブ複数ある場合に対応

**Comment by ryojiroakiyama** [comment]
一旦key(listen_fd)はstringで

**Comment by kohkubo** [comment]
複数に関わらず、std::vector<ServerConfig>みたいな形で決まりそうなら

```c++
int main(int argc, char **argv) {
  const char  *config_file_path = get_config_file_path(argc, argv);
  std::vector<ServerConfig> server_configs    = read_config_file(config_file_path);
  server_io_multiplexing(server_configs[0]);
  return (0);
}
```
一旦、現状の実装に合わせて、これで動くようなものをコミットできないですか?

**Comment by kohkubo** [comment]
↑話し合い済みとのこと了解しました。
