### ISSUE TITLE
パーセントエンコーディング実装（必要か要確認

### ISSUE THREAD

**Issue by nakamo326** [kohkubo/webserv#305]

**Comment by kohkubo** [comment]
C/C++でパーセントエンコーディング・デコーディングをする
https://gist.github.com/sasairc/20ffb55dbe225dbd6a8258f7a2f92a38

**Comment by ryojiroakiyama** [comment]
分かっていること
- 特殊文字についてエンコードすることをパーセントエンコーディングと呼ぶ場合がある
- リンク集  
https://developer.mozilla.org/ja/docs/Glossary/percent-encoding  
https://tex2e.github.io/rfc-translater/html/rfc3986.html  
https://e-words.jp/w/URL%E3%82%A8%E3%83%B3%E3%82%B3%E3%83%BC%E3%83%89.html  
- 作り途中のbranch名 [feat/percent_encoding](https://github.com/kohkubo/webserv/tree/feat/percent_encoding)
