### ISSUE TITLE
itestリファクタ

### ISSUE THREAD

**Issue by kohkubo** [kohkubo/webserv#385]

**Comment by ryojiroakiyama** [comment]
configを引数で渡す
テストの開始と改行を入れる関数に通す

**Comment by ryojiroakiyama** [comment]
utils.goを別へ移動

**Comment by ryojiroakiyama** [comment]
GET()で実行する時にGETの名前を取って出力する
https://stackoverflow.com/questions/7052693/how-to-get-the-name-of-a-function-in-go
