### ISSUE TITLE
レスポンス/リクエストのメッセージの終わりの判断材料がわからない

### ISSUE THREAD

**Issue by ryojiroakiyama** [kohkubo/webserv#39]

**Comment by ryojiroakiyama** [comment]
おおくぼさんが参考にしていたコードではCRLFが

**Comment by kohkubo** [comment]
```
HTTP/1.1 200 OK\r\n\
Content-Type: text/html\r\n\
Content-Length: 59\r\n\
```

ヘッダーで長さを連携しているから、そこで判断している？

**Comment by kohkubo** [comment]
```
            if( (recv_str[recv_str.length()-4] == 0x0d) &&
            (recv_str[recv_str.length()-3] == 0x0a) &&
            (recv_str[recv_str.length()-2] == 0x0d) &&
            (recv_str[recv_str.length()-1] == 0x0a)
            ){
                break;
            }
```

ここ

**Comment by ryojiroakiyama** [comment]
それです！ありがとうございます！
要検討ですね

**Comment by kohkubo** [comment]
自分のコードだとここ！

```
    if (is_match_suffix_string(__recv_str, "\r\n\r\n")) {
      break;
    }
```

**Comment by kohkubo** [comment]
参考にしているコードはエラー処理をしていないから危ないコードかも。

**Comment by ryojiroakiyama** [comment]
おけです！
そしたらあくまで枠組み程度で捉えて読みます。
と言っても月曜に理解するつもりですが。

**Comment by kohkubo** [comment]
https://www.ibm.com/docs/ja/ibm-mq/8.0?topic=ssfksj-8-0-0-com-ibm-mq-ref-dev-doc-q110660--htm

**Comment by ryojiroakiyama** [comment]
長らく放置してしまってすみませんでした。
メッセージの終わり(ボディの終わり)に関して, ヘッダーフィールドのContent-Lengthで判断するでいいと思います。
エンコードなど必要なボディになるとまた話が変わりそうですが([RFC7230](https://tex2e.github.io/rfc-translater/html/rfc7230.html)の3.3.2参照), 現状はこれで進めるのでissueを閉じます。

参考にしたのは
RFC7230
3.Message Format
> メッセージ本文が示されている場合は、メッセージ本文の長さに等しいオクテットの量が読み取られるか、接続が閉じられるまで、ストリームとして読み取られます。

3.3.2. Content-Length
> ペイロード本文を含むメッセージの場合、Content-Lengthフィールド値は、本文（およびメッセージ）の終了位置を決定するために必要なフレーミング情報を提供します。
