### ISSUE TITLE
プライベート関数のユニットテスト

### ISSUE THREAD

**Issue by kohkubo** [kohkubo/webserv#84]

**Comment by nakamo326** [comment]
https://stackoverflow.com/a/47358700/17818913
ここら辺が参考になると思います。
https://t-wada.hatenablog.jp/entry/should-we-test-private-methods
なるべくprivateメソッドのテスト書かないほうがよさそうです。

**Comment by kohkubo** [comment]
そうですね。is_piとかを外に出したので、それで良さそうですね！
